# Base URL used when generating links to your pages
# Set to the URL for your site
baseURL = "https://example.com"

# Basic metadata configuration for your blog.
theme = "rtc"
title = "Research and Teaching Companion"
author = "Jane Doe"
copyright = "Copyright © 2020, Jane Doe."
languageCode = "en-US"

# Generate robots.txt for SEO
enableRobotsTXT = true

refLinksErrorLevel = "WARNING"