# Base URL used when generating links to your pages
# Set to the URL for your site
baseURL = "https://teaching640.makingandknowing.org/"
canonifyURLs = true

# Basic metadata configuration for your blog.
theme = "rtc"
title = "Research and Teaching Companion"
author = "Columbia University"
copyright = "Copyright © 2024, Columbia University"
languageCode = "en-US"

# Generate robots.txt for SEO
enableRobotsTXT = true

# Set to "WARNING" so that broken links don't break the build process. Default is "ERROR".
refLinksErrorLevel = "WARNING"

# turn on unsafe handling to pass through raw html
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Google analytics code
googleAnalytics = "YOUR-TRACKING-ID"
